server:
    port: 5001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    datasource:
      url: jdbc:mysql://localhost:3307/bankAccount?createDatabaseIfNotExist=true
      username: root
      password: root

kafka:
    listener:
        ack-mode: MANUAL_IMMEDIATE
    consumer:
        bootstrap-servers: localhost:9093
        group-id: bankaccConsumer
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.support.serializer.JsonDeserializer
        properties:
            spring.json.trusted.packages: '*'