server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: bankAccount
  kafka:
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer